apiVersion: v1
kind: Service
metadata:
  name: win-sample
  labels:
    app: win-sample
spec:
  ports:
    # the port that this service should serve on
    - port: 8000
      targetPort: 80
  selector:
    app: win-sample
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-sample
  name: win-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: win-sample
  template:
    metadata:
      labels:
        app: win-sample
      name: win-sample
    spec:
     containers:
      - name: win-sample
        image: mcr.microsoft.com/dotnet/samples:aspnetapp        
     nodeSelector:
      kubernetes.io/os: windows